---
title: "CompetitionRegressionByDefenseOffice"
author: "SRC"
date: "Wednesday, June 10, 2015"
output: html_document
---

```{r hiddensetup, echo = FALSE}
require(ggplot2)
require(stringr)
require(plyr)
require(Hmisc)
require(texreg)
options(error=recover)
setwd("K:\\Development\\Competition")
# setwd("C:\\Users\\Greg Sanders\\Documents\\Development\\Fixed-price")
#setwd("C:/Users/scohen/My Documents/Competition/Competition/")
Path<-"K:\\2007-01 PROFESSIONAL SERVICES\\R scripts and data\\"
# Path<-"C:\\Users\\Greg Sanders\\SkyDrive\\Documents\\R Scripts and Data SkyDrive\\"
#path <- "C:/Users/scohen/My Documents/Competition/Competition/"
source(paste(Path,"lookups.r",sep=""))
layout(matrix(c(1,2,3,4),2,2))
```


```{r setup}
KOfflist  <- read.csv(
    paste("data\\defense_office_competition_combined.csv", sep = ""),
    header = TRUE, sep = ",", dec = ".", strip.white = TRUE, 
    na.strings = c("NULL","NA",""),
    stringsAsFactors = TRUE
    )


KOfflist <- KOfflist[KOfflist$Exclude == "FALSE", ] 

names(KOfflist)


```

